# [[mgr.prepend_keymap]]
# on   = [ "g", "d" ]
# run  = "cd ~/Downloads"
# desc = "Cd to ~/Downloads"

[[mgr.prepend_keymap]]
on   = [ "g", "p" ]
run  = "cd ~/Pictures"
desc = "Cd to ~/Pictures"

[[mgr.prepend_keymap]]
on   = [ "g", "P" ]
run  = "cd ~/Projects/"
desc = "Cd to ~/Projects/"

[[mgr.prepend_keymap]]
on = "<C-y>"
run = ["plugin wl-clipboard"]
